### ISSUE TITLE
Feature: 3D Models with Physics

### ISSUE THREAD

**Issue by philipdoucla** [CS-130-Winter-2024/balhalla#11]
## User Story
As a **developer**, I would like **a 3D environment with models that follow physics** so that **the game can have interactions necessary for dodgeball**.

## Detailed Description
The game will be 3D with physics collisions between players. Players have an individual first person camera. Players can throw a ball, which will move according to physics.

## Acceptance Criteria
- [x] Given **asset models**, then **the game assets can be viewed in 3D on a web browser**
- [x] Given **a camera position**, then **the player can see 3D models in a first person perspective**
- [x] Given **a ball is thrown**, then **the ball should follow projectile motion**
- [x] Given **models make contact**, then **there should be a collision detected**
- [x] Given **a collision is detected**, then **the corresponding effect should occur for each model**

**Comment by Big-Cheung** [comment]
Notes on collision detection:

Use a cylindrical hitbox player and a spherical ball of a constant radius for all models.
Collision detection itself will be handled by the server handling websockets (Game server).

Using radial hitboxes is much more performant.
