### ISSUE TITLE
Feature: Player Controls

### ISSUE THREAD

**Issue by philipdoucla** [CS-130-Winter-2024/balhalla#12]
## User Story
As a **player**, I would like **to control my character** so that **I can interact with the game**.

## Detailed Description
The player should be able to move around, look around the environment with the mouse, throw a ball, and dash to dodge a ball.

## Acceptance Criteria
- [x] Given **keyboard inputs of 'W', 'A', 'S', or 'D'**, then **the character model should move forward, backward, left, or right respectively**
- [x] Given **mouse movement**, then **the camera view should change accordingly**
- [x] Given **keyboard input of 'Space'**, then **a ball should be thrown**
- [x] Given **keyboard input of 'Shift'**, then **the character model should dash in the current movement direction**

**Comment by Big-Cheung** [comment]
Done.  See #23 and #24
