### ISSUE TITLE
Feature: Web Server Database Access

### ISSUE THREAD

**Issue by philipdoucla** [CS-130-Winter-2024/balhalla#15]
## User Story
As a **developer**, I would like **the web server to access records from the database** so that **a player's stats and credits can be updated**.

## Detailed Description
We need to have the web server be able to access the database to make updates to the player's accounts as necessary to display the correct statistics and credits for each player.

## Acceptance Criteria
- [x] Given **a functional accounts database**, then **the web server should be able to update database records**

**Comment by philipdoucla** [comment]
Database accessible after creation of schema

**Comment by philipdoucla** [comment]
Reopening due to need to integrate with web server

**Comment by dhavalvoraa** [comment]
Functions have been created, TODO: insert functions in web server
