### ISSUE TITLE
Feature: Account Registration

### ISSUE THREAD

**Issue by philipdoucla** [CS-130-Winter-2024/balhalla#7]
## User Story
As a **user**, I would like **to be able to register with my info** so that **I can make an account**.

## Detailed Description
Users can register for an account that is keyed by their email address.

## Acceptance Criteria
- [x] Given **a user has an unregistered email and password**, then **they can register for an account**

**Comment by dhavalvoraa** [comment]
Login/Signup functions and db access have been merged in
